Word Embedding: (Feature Reprsentaion for the words in the sentence)

It is low Dimention, matrix is dense

Tradionally we are using Bag of words(Not getting any semantic Information), TF-IDF(Bit of Semantic information) One hot Encoding(Matrix is Sprase, High Demntion).

However, this methods that certain disadvantage
1) It creates Sparse Matrix(One hot encoding has only one ones and lot of zeros)2) High Dimention


In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

**One Hot Encoding**

In [5]:

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9982, 3009, 1752, 3933], [9982, 3009, 1752, 7395], [9982, 6141, 1752, 2860], [9407, 5222, 5852, 8799, 2108], [9407, 5222, 5852, 8799, 2865], [5462, 9982, 1019, 1752, 4988], [7343, 6752, 9118, 8799]]


**Word Embedding Represntation**

In [7]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:

sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9982 3009 1752 3933]
 [   0    0    0    0 9982 3009 1752 7395]
 [   0    0    0    0 9982 6141 1752 2860]
 [   0    0    0 9407 5222 5852 8799 2108]
 [   0    0    0 9407 5222 5852 8799 2865]
 [   0    0    0 5462 9982 1019 1752 4988]
 [   0    0    0    0 7343 6752 9118 8799]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995
    0.01334566 -0.03420538  0.00280726 -0.0154354  -0.02989644]
  [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995
    0.01334566 -0.03420538  0.00280726 -0.0154354  -0.02989644]
  [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995
    0.01334566 -0.03420538  0.00280726 -0.0154354  -0.02989644]
  [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995
    0.01334566 -0.03420538  0.00280726 -0.0154354  -0.02989644]
  [ 0.03725007 -0.0019477   0.04354865 -0.02032383 -0.04179283
    0.00773787 -0.0350861  -0.0286567   0.00862188 -0.0137329 ]
  [ 0.01920333 -0.02743528  0.00261362 -0.01356976 -0.02055472
   -0.00926069 -0.018743   -0.00023341 -0.00342776  0.00698287]
  [-0.02240461  0.04068254  0.02276129  0.00035008 -0.00938362
   -0.01728473  0.0086052  -0.03622813  0.01711674 -0.02975123]
  [-0.04552461  0.02815037 -0.02010936  0.03436759 -0.04847533
    0.01459576  0.03218055  0.03047149 -0.040410

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9982, 3009, 1752, 3933], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995  0.01334566
  -0.03420538  0.00280726 -0.0154354  -0.02989644]
 [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995  0.01334566
  -0.03420538  0.00280726 -0.0154354  -0.02989644]
 [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995  0.01334566
  -0.03420538  0.00280726 -0.0154354  -0.02989644]
 [ 0.01174831 -0.02187335 -0.04276012  0.02391887  0.01428995  0.01334566
  -0.03420538  0.00280726 -0.0154354  -0.02989644]
 [ 0.03725007 -0.0019477   0.04354865 -0.02032383 -0.04179283  0.00773787
  -0.0350861  -0.0286567   0.00862188 -0.0137329 ]
 [ 0.01920333 -0.02743528  0.00261362 -0.01356976 -0.02055472 -0.00926069
  -0.018743   -0.00023341 -0.00342776  0.00698287]
 [-0.02240461  0.04068254  0.02276129  0.00035008 -0.00938362 -0.01728473
   0.0086052  -0.03622813  0.01711674 -0.02975123]
 [-0.04552461  0.02815037 -0.02010936  0.03436759 -0.04847533  0.01459576
   0.03218055  0.03047149 -0.04041048 -0.01517069]]

Note: When are converting the word to two dimentions we can check how each work is related with other. By Anlysing it......